export enum AttachmentErrorCode {
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  INVALID_ATTACHMENT_TYPE = 'INVALID_ATTACHMENT_TYPE',
  MIME_TYPE_NOT_ALLOWED = 'MIME_TYPE_NOT_ALLOWED',
  MIME_MISMATCH = 'MIME_MISMATCH',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE = 'INVALID_FILE',
  UPLOAD_STRATEGY_NOT_ALLOWED = 'UPLOAD_STRATEGY_NOT_ALLOWED',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  PRESIGN_EXPIRED = 'PRESIGN_EXPIRED',
  UPLOAD_NOT_FOUND_IN_STORAGE = 'UPLOAD_NOT_FOUND_IN_STORAGE',
  NOT_OWNER = 'NOT_OWNER',
}
