/**
 * AuthErrorCode — authoritative source for the auth bounded context.
 *
 * Note: `EMAIL_ALREADY_REGISTERED` / `LICENSE_ALREADY_REGISTERED` are NOT here.
 * Signup never pre-checks; the doctor persistence layer raises those conflicts
 * as `DoctorErrorCode`, so declaring them again would be a duplicate string
 * value in the union. Auth simply lets them propagate.
 */
export enum AuthErrorCode {
  // Login
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCOUNT_NOT_ACTIVE = 'ACCOUNT_NOT_ACTIVE',

  // Email verification link
  VERIFICATION_TOKEN_INVALID = 'VERIFICATION_TOKEN_INVALID',
  VERIFICATION_TOKEN_EXPIRED = 'VERIFICATION_TOKEN_EXPIRED',

  // Password reset link
  RESET_TOKEN_INVALID = 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',

  // Password management
  PASSWORD_ALREADY_SET = 'PASSWORD_ALREADY_SET',
  CURRENT_PASSWORD_INCORRECT = 'CURRENT_PASSWORD_INCORRECT',

  // OAuth
  PROVIDER_EMAIL_NOT_VERIFIED = 'PROVIDER_EMAIL_NOT_VERIFIED',
  OAUTH_PROVIDER_NOT_SUPPORTED = 'OAUTH_PROVIDER_NOT_SUPPORTED',
  OAUTH_STATE_MISMATCH = 'OAUTH_STATE_MISMATCH',
  OAUTH_ACCOUNT_ALREADY_LINKED = 'OAUTH_ACCOUNT_ALREADY_LINKED',
  OAUTH_PROVIDER_NOT_LINKED = 'OAUTH_PROVIDER_NOT_LINKED',
  CANNOT_UNLINK_LAST_AUTH_METHOD = 'CANNOT_UNLINK_LAST_AUTH_METHOD',
  REGISTRATION_TICKET_INVALID = 'REGISTRATION_TICKET_INVALID',
  REGISTRATION_TICKET_EXPIRED = 'REGISTRATION_TICKET_EXPIRED',

  // Guards
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  KYC_NOT_VERIFIED = 'KYC_NOT_VERIFIED',
}
