export enum DoctorErrorCode {
  DOCTOR_NOT_FOUND = 'DOCTOR_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  KYC_ALREADY_SUBMITTED = 'KYC_ALREADY_SUBMITTED',
  KYC_NOT_VERIFIED = 'KYC_NOT_VERIFIED',
}
