/**
 * NotificationErrorCode — authoritative source for the notification context.
 */
export enum NotificationErrorCode {
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ALREADY_SENT = 'NOTIFICATION_ALREADY_SENT',
  INVALID_DELIVERY_TRANSITION = 'INVALID_DELIVERY_TRANSITION',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_RENDER_FAILED = 'TEMPLATE_RENDER_FAILED',
  UNSUPPORTED_CHANNEL = 'UNSUPPORTED_CHANNEL',
  CHANNEL_SEND_FAILED = 'CHANNEL_SEND_FAILED',
  INVALID_RECIPIENT = 'INVALID_RECIPIENT',
}
