export enum PatientErrorCode {
  // Identity
  PATIENT_NOT_FOUND      = 'PATIENT_NOT_FOUND',
  NIN_ALREADY_REGISTERED = 'NIN_ALREADY_REGISTERED',

  // Field-level domain violations (thrown by VOs on semantically bad data)
  INVALID_FULL_NAME         = 'INVALID_FULL_NAME',
  INVALID_DATE_OF_BIRTH     = 'INVALID_DATE_OF_BIRTH',
  INVALID_BLOOD_TYPE        = 'INVALID_BLOOD_TYPE',
  INVALID_NIN               = 'INVALID_NIN',
  INVALID_EMERGENCY_CONTACT = 'INVALID_EMERGENCY_CONTACT',
  INVALID_ALLERGY           = 'INVALID_ALLERGY',
  INVALID_CHRONIC_DISEASE   = 'INVALID_CHRONIC_DISEASE',
}
