/**
 * DoctorErrorCode — authoritative source of truth for this bounded context.
 * Re-exported by `common/errors/codes` so it joins the global `ErrorCode` union
 * that `DomainError` accepts.
 */
export enum DoctorErrorCode {
  DOCTOR_NOT_FOUND = 'DOCTOR_NOT_FOUND',
  DOCTOR_PROFILE_NOT_FOUND = 'DOCTOR_PROFILE_NOT_FOUND',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  LICENSE_ALREADY_REGISTERED = 'LICENSE_ALREADY_REGISTERED',
  INVALID_VERIFICATION_TRANSITION = 'INVALID_VERIFICATION_TRANSITION',
  VERIFICATION_REASON_REQUIRED = 'VERIFICATION_REASON_REQUIRED',
  VERIFICATION_DOCUMENTS_MISSING = 'VERIFICATION_DOCUMENTS_MISSING',
  DEPARTMENT_NOT_APPLICABLE = 'DEPARTMENT_NOT_APPLICABLE',
  INVALID_SCHEDULE_RANGE = 'INVALID_SCHEDULE_RANGE',
  DUPLICATE_SCHEDULE_DAY = 'DUPLICATE_SCHEDULE_DAY',
  INVALID_EDUCATION_YEAR = 'INVALID_EDUCATION_YEAR',
  TOO_MANY_EXPERTISE_ITEMS = 'TOO_MANY_EXPERTISE_ITEMS',
  TOO_MANY_LANGUAGES = 'TOO_MANY_LANGUAGES',
  TOO_MANY_EDUCATION_ENTRIES = 'TOO_MANY_EDUCATION_ENTRIES',

  // Integrity guards for restoreExisting() (untrusted DB values) + the
  // affiliation "independent has no workplace name" rule.
  INVALID_ACCOUNT_STATUS = 'INVALID_ACCOUNT_STATUS',
  INVALID_VERIFICATION_STATUS = 'INVALID_VERIFICATION_STATUS',
  INVALID_WORKPLACE_TYPE = 'INVALID_WORKPLACE_TYPE',
  WORKPLACE_NAME_NOT_APPLICABLE = 'WORKPLACE_NAME_NOT_APPLICABLE',
}
